import Sidebar from '@/app/_components/Sidebar';
import '@/app/globals.css';
import { Noto_Sans_JP } from 'next/font/google';

const notoSansJapanese = Noto_Sans_JP({
  preload: false,
  weight: ['400', '600'],
});

// TODO
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" data-theme="winter">
      <body className={notoSansJapanese.className}>
        <Sidebar></Sidebar>
        <main className="py-10 lg:pl-72">
          <div className="px-4 sm:px-6 lg:px-8">{children}</div>
        </main>
      </body>
    </html>
  );
}
