import {
  Bars3Icon,
  Cog8ToothIcon,
  GiftIcon,
  HomeIcon,
  MagnifyingGlassIcon,
  QuestionMarkCircleIcon,
} from '@heroicons/react/24/solid';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

// TODO
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" data-theme="garden">
      <body className={inter.className}>
        <div className="drawer lg:drawer-open">
          <input id="drawer" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col">
            <div className="navbar w-full bg-base-200 lg:hidden">
              <div className="flex-none">
                <label htmlFor="drawer" className="btn-ghost btn-square btn">
                  <Bars3Icon className="h-6 w-6"></Bars3Icon>
                </label>
              </div>
              <div className="mx-2 flex-1 px-2">ロゴ</div>
            </div>
            {children}
          </div>
          <nav className="drawer-side">
            <label htmlFor="drawer" className="drawer-overlay"></label>
            <div className="flex h-screen w-64 flex-col bg-base-200">
              <div className="sticky top-0 z-20 hidden lg:flex">
                <div className="text-lg">ロゴ</div>
              </div>
              <ul className="menu flex-nowrap p-4">
                <li>
                  <a>
                    <HomeIcon className="h-6 w-6"></HomeIcon>
                    ダッシュボード
                  </a>
                </li>
                <li>
                  <a>
                    <MagnifyingGlassIcon className="h-6 w-6"></MagnifyingGlassIcon>
                    AITuber
                  </a>
                </li>
                <li>
                  <a>
                    <GiftIcon className="h-6 w-6"></GiftIcon>
                    ポイント受取
                  </a>
                </li>
                <li>
                  <a>
                    <QuestionMarkCircleIcon className="h-6 w-6"></QuestionMarkCircleIcon>
                    ヘルプ
                  </a>
                </li>
                <li>
                  <a>
                    <Cog8ToothIcon className="h-6 w-6"></Cog8ToothIcon>
                    設定
                  </a>
                </li>
              </ul>
              <div className="m-4 mt-auto flex h-20 items-center gap-3">
                <div className="flex h-full w-20 items-center justify-center rounded-full bg-white">
                  画像
                </div>
                <div className="flex flex-col">
                  <div className="flex items-center text-sm font-semibold">
                    ああああああああ
                  </div>
                  <div className="flex items-center text-sm font-semibold">
                    ID:11111111
                  </div>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </body>
    </html>
  );
}
