import '@/app/globals.css';
import classNames from 'classnames';
import { Noto_Sans_JP } from 'next/font/google';

const notoSansJapanese = Noto_Sans_JP({
  preload: false,
  weight: ['400', '600'],
});

// TODO
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function StreamLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" data-theme="winter">
      <body className={classNames(notoSansJapanese.className, 'bg-green-500')}>
        <main>
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
}
