name: Deploy API
on: pull_request

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: "actions/checkout@v3"
      - name: Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      - name: Get version
        run: echo "VERSION=$(date +%s)" >> $GITHUB_ENV
      - name: Deploy GAE
        id: deploy-app
        uses: "google-github-actions/deploy-appengine@v1"
        with:
          working_directory: "./api"
          deliverables: "app.yaml"
          version: v1
          env_vars: |-
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            VERSION=${{ env.VERSION }}
            YOUTUBE_DATA_API_KEY=${{ secrets.YOUTUBE_DATA_API_KEY }}
